--liquibase formatted sql

--changeset Nazrul:001-initial-schema.sql
CREATE TABLE IF NOT EXISTS users
(
    id               uuid                        NOT NULL,
    created_at       timestamp without time zone NOT NULL,
    domain_id        bigint                      NOT NULL,
    event_type       character varying           NOT NULL,
    initiated_by     bigint                      NOT NULL,
    associated_model bigint                      NOT NULL,
    PRIMARY KEY (id)
    );



CREATE TABLE IF NOT EXISTS initiators
(
    id          bigint            NOT NULL generated by default AS IDENTITY primary key,
    external_id character varying NOT NULL,
    type        character varying NOT NULL
);